services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --dir /data --dbfilename dump.rdb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - redis-network
    user: redis

  mcp-server:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    stdin_open: true
    tty: true
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data:
    driver: local 